# Generated by Django 4.0.3 on 2022-05-26 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_geolocation_latitude_geolocation_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='custom',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
