# Generated by Django 4.0.3 on 2022-05-26 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_custom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custom',
            old_name='id',
            new_name='Id',
        ),
    ]
