# Generated by Django 4.0.3 on 2022-05-26 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_geolocation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom',
            name='email',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='custom',
            name='first_name',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='custom',
            name='last_name',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='custom',
            name='password',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
