# Generated by Django 4.0.3 on 2022-05-26 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_custom_email_custom_first_name_custom_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom',
            name='phone',
            field=models.IntegerField(default=9876543210, max_length=10),
        ),
    ]
