# Generated by Django 4.0.3 on 2022-05-26 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_custom_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom',
            name='phone',
            field=models.DecimalField(decimal_places=0, default=9876543210, max_digits=10),
        ),
    ]
