# Generated by Django 4.0.3 on 2022-05-26 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_custom_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom',
            name='email',
        ),
        migrations.RemoveField(
            model_name='custom',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='custom',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='custom',
            name='password',
        ),
        migrations.RemoveField(
            model_name='custom',
            name='phone',
        ),
    ]
