# Generated by Django 4.0.3 on 2022-05-26 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_custom_email_remove_custom_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custom',
            old_name='Id',
            new_name='id',
        ),
    ]
