# Generated by Django 4.0.3 on 2022-05-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_geolocation_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='custom',
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='Id',
            field=models.CharField(default='id1', max_length=10),
        ),
    ]
