# Generated by Django 4.0.3 on 2022-05-26 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='geolocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.IntegerField()),
                ('Name', models.CharField(default='a', max_length=200)),
                ('Latitude', models.DecimalField(decimal_places=8, default=0, max_digits=12)),
                ('Longitude', models.DecimalField(decimal_places=8, default=0, max_digits=12)),
            ],
        ),
    ]
